### PR TITLE
update ref47, line color changed

### PR DESCRIPTION
**Pull request by jks-liu**
Releated commit JuliaPlots/Plots.jl@5cca5e9148724832b405925d36125b909deb3efb

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
I am a bit puzzled why tests pass regardless

**Comment by jks-liu** [comment]
It seems in recent commits all Julia 1 CI tests passed, but all Julia nightly test failed. Do not know why.

FYI: I use v1.6.1 now.

**Comment by BeastyBlacksmith** [comment]
Fails on nightly are unrelated to this

**Comment by t-bltg** [comment]
> I am a bit puzzled why tests pass regardless

`image_comparison_tests` [tolerance](https://github.com/JuliaPlots/Plots.jl/blob/7bb2a293565a6b8ab8af48f73c86b61bf72fc5db/test/imgcomp.jl#L25) :wink:

Before https://github.com/JuliaPlots/Plots.jl/commit/5cca5e9148724832b405925d36125b909deb3efb:
`Reference image /home/runner/.julia/dev/PlotReferenceImages/Plots/gr/1.11.2/ref47.png matches.  Difference: 0.0`

After:
`Reference image /home/runner/.julia/dev/PlotReferenceImages/Plots/gr/1.11.2/ref47.png matches.  Difference: 0.0045264139433550095`

**Comment by t-bltg** [comment]
Thanks @jks-liu !

**Pull request merged**
