### PR TITLE
add reference image for lens recipe

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**

### CODE REVIEW

**Comment by daschw** [comment]
Nice, it looks like this:

Should we maybe move the legend or the inset in another corner?

**Comment by BeastyBlacksmith** [comment]
you are right, I think `legend = :outertopright` would be a good fit

**Comment by daschw** [comment]
Good idea, I think we are not testing `:outer` legend positions yet.

**Comment by BeastyBlacksmith** [comment]
Is this expected behaviour (the inset shifted)? I thought the relative bounding box is relative to the plotarea.
image

**Comment by daschw** [comment]
I thought so too.
I will have a deeper look into the interplay of GR and plotarea at vizcon anyway. I think for now we can add the reference image like this and update it when we hopefully fix it.

**Comment by BeastyBlacksmith** [comment]
I think you merged the old image ._.

**Comment by daschw** [comment]
Oh, thanks!

**Pull request merged**
