### PR TITLE
Colorbar label copies font style from Y Axis

### PR DESCRIPTION
**Pull request by AnkurD**

### CODE REVIEW

**Comment by AnkurD** [comment]
Generated from this pull request: https://github.com/JuliaPlots/Plots.jl/pull/1108

**Comment by mkborregaard** [comment]
sorry for being slow, but why are so many plots without color bars affected by this?

**Comment by mkborregaard** [comment]
and why a gr plot? It sounds like there is some versioning issue here?

**Comment by AnkurD** [comment]
Some of the plots had no discernible changes, yet they popped up. As for GR I also could not determine any noticeable different, so yes it might have been versioning, but I had checked out the most current master branch before I started.

**Comment by daschw** [comment]
I restarted the travis build. I think if it passes, it should be fine.
For me e.g. the Plots look a little different when I run them from windows compared to running them from linux. Maybe it is related to system configuration or something similar.
Also the local RegressionTests require a more accurate image matching than the travis tests.

**Comment by daschw** [comment]
The tests fail because of pyplot/ref18.png.
Apparently you were not too slow, @mkborregaard, but I was to fast with merging. I will run the tests again at my linux workstation today in the evening.

**Comment by daschw** [comment]
When I run the tests locally, I get the exact same results. Travis, however, keeps failing on pyplot/18 in https://github.com/JuliaPlots/Plots.jl/pull/1108.
I have no idea, why ... This is really weird.
Any ideas @mkborregaard on how to proceed? Should I revert the merge for now?

**Comment by mkborregaard** [comment]
Yes, I'd suggest reverting this, then make a new PR that only updates the plots that we'd expect the PR to change. It is possible that a PR has been merged to Plots that changed some behaviour without a corresponding PlotReferenceImages PR, so the first step would be to run the tests on current master and see if they correspond to master of PlotReferenceImages (after reverting).

**Pull request merged**
