### PR TITLE
Update reference image for nightly

### PR DESCRIPTION
**Pull request by t-bltg**

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
Why are they different on nightly and do the new versions also pass CI on current stable?

**Comment by t-bltg** [comment]
Yes they do pass current stable, I only reduced the tolerance there.

For nightly I suspect that there is a change in the random number generator since failing ref 1, 17 and 18 do use lots of random numbers compared to other examples.

**Comment by BeastyBlacksmith** [comment]
I would prefer that we use StableRNG.jl then

**Comment by t-bltg** [comment]
Good idea.

**Comment by t-bltg** [comment]
Is no very easy to reproduce, since we don't have access to the failing images of the CI. I should try to build a nightly version of julia I guess.

**Comment by t-bltg** [comment]
For my reference: https://github.com/JuliaPlots/Plots.jl/runs/2949842069 is one of the first traces of failing 1, 17, 18, and this was using `Julia Version 1.8.0-DEV.100`.

**Comment by t-bltg** [comment]
I see what is going on here: `fakedata(...)` isn't fixed by `fix_rand!`.

**Pull request merged**
